### ISSUE TITLE
Request for an alternate version

### ISSUE THREAD

**Issue by Treearecool** [tebl/Christmas-2020#1]
Hello,

I really like how the tree looks and works, but i am reluctant to create multiple of them to gift them out to my friends and family. Is it possible that you can create a battery powered version of the Part C board, perhaps with a CR2032-BS-5-1 connector, that simply powers the tree, without it blinking? It could keep costs down and would still look good as a gift.

Thanks!

**Comment by tebl** [comment]
If you already have part C, then you could do that with a few wires though I realize that might scare most that aren't used to DIY projects (see https://github.com/tebl/Christmas-2020/raw/main/gallery/Screenshot%202020-11-14%20233453.png for example). I threw together a part C2 like you described - could not use the part you specified as I do not have it, also it is meant to be installed vertically instead of flat on a board. Did an option for the generic black flat chinese CR2032 holder instead as well as a MicroUSB breakout module (see https://github.com/tebl/Christmas-2020/raw/main/gallery/2020-11-14%2023.36.01.jpg for picture).

**Comment by Treearecool** [comment]
Thank You Very Much.
